#ifndef DATA_TOPIC_REGISTRY_HPP
#define DATA_TOPIC_REGISTRY_HPP
// ============================================================================
// topic_registry.hpp — Centralized ZMQ Topic Routing Table
//
// Defines all 22 ZMQ PUB topics with their routing metadata. Provides:
//   - O(1) lookup by topic ID (array index)
//   - O(1) lookup by sensor ID (for UART-originated data)
//   - Publish policy, threshold, and period configuration
//   - Topic source classification (UART from MCU vs host-generated SYSTEM)
//
// All data is constexpr — zero runtime cost, immutable at compile time.
// ============================================================================

#include "oro_protocol.hpp"
#include <array>
#include <cstdint>

namespace oro {

// ── Topic Categories ────────────────────────────────────────────────────────

enum class TopicCategory : uint8_t {
  ANALOG,   // Float-valued sensors (weight, level, temp, humidity, battery)
  DIGITAL,  // Binary/state sensors (switches, states, heartbeat)
  ENCODER,  // Signed tick count (optical encoder)
  THERMAL,  // 8x8 IR Array frame data (AMG8833)
  HEARTBEAT // MCU Aliveness signal with sequence increment monitoring
};

// ── Publish Policies ────────────────────────────────────────────────────────

enum class PublishPolicy : uint8_t {
  ON_CHANGE,    // Publish only when state changes (digital sensors)
  ON_THRESHOLD, // Publish when value delta exceeds threshold (analog sensors)
  PERIODIC,     // Publish at fixed intervals regardless of change
  CONTINUOUS,   // Publish every incoming reading (encoder while active)
  ON_UPDATE     // Publish only when explicitly updated (display, clock)
};

// ── Topic Data Source ───────────────────────────────────────────────────────

enum class TopicSource : uint8_t {
  UART,  // Data originates from MCU via serial OroPacket
  SYSTEM // Data is generated by the host (clock, connectivity)
};

// ── Topic Descriptor ────────────────────────────────────────────────────────

struct TopicDescriptor {
  uint8_t topic_id;       // Index into TOPIC_REGISTRY
  TopicCategory category; // Payload type selector
  PublishPolicy policy;   // When to publish
  TopicSource source;     // Where data comes from
  const char *zmq_topic;  // ZMQ topic string (Frame 0)
  float threshold;        // Meaningful delta for ON_THRESHOLD (0.0 if N/A)
  uint32_t period_ms;     // Interval for PERIODIC/fallback (0 if N/A)
  int8_t sensor_id;       // Mapped SensorID for UART sources (-1 if SYSTEM)
};

// ── Topic IDs ───────────────────────────────────────────────────────────────

static constexpr uint8_t TID_FOOD_WEIGHT_BOWL_1 = 0;
static constexpr uint8_t TID_FOOD_WEIGHT_BOWL_2 = 1;
static constexpr uint8_t TID_WATER_LEVEL_TANK = 2;
static constexpr uint8_t TID_WATER_LEVEL_BOWL = 3;
static constexpr uint8_t TID_HUMIDITY = 4;
static constexpr uint8_t TID_TEMPERATURE = 5;
static constexpr uint8_t TID_LIMIT_SWITCH_1 = 6;
static constexpr uint8_t TID_LIMIT_SWITCH_2 = 7;
static constexpr uint8_t TID_OPTICAL_ENCODER = 8;
static constexpr uint8_t TID_HOME_SENSOR = 9;
static constexpr uint8_t TID_POWER_SWITCH = 10;
static constexpr uint8_t TID_BATTERY_LEVEL = 11;
static constexpr uint8_t TID_CLOCK = 12;
static constexpr uint8_t TID_HEARTBEAT = 13;
static constexpr uint8_t TID_CONNECTIVITY = 14;
static constexpr uint8_t TID_LID_1 = 15;
static constexpr uint8_t TID_LID_2 = 16;
static constexpr uint8_t TID_WATER_PUMP = 17;
static constexpr uint8_t TID_STEPPER_MOTOR = 18;
static constexpr uint8_t TID_SEVEN_SEGMENT = 19;
static constexpr uint8_t TID_LED_INDICATOR = 20;
static constexpr uint8_t TID_CMD_CAMERA_ROTATION = 21;
static constexpr uint8_t TID_CMD_FEED = 22;
static constexpr uint8_t TID_CMD_TREAT = 23;
static constexpr uint8_t TID_CMD_PHOTO = 24;
static constexpr uint8_t TID_CMD_LIVE_START = 25;
static constexpr uint8_t TID_CMD_LIVE_END = 26;
static constexpr uint8_t TID_CMD_CAMERA_IR = 27;
static constexpr uint8_t TID_CMD_AUDIO = 28;
static constexpr uint8_t TID_CMD_SETTINGS = 29;
static constexpr uint8_t TID_CMD_FW_UPDATE = 30;
static constexpr uint8_t TID_TREAT_LEVEL_IR = 31;
static constexpr uint8_t TID_TREAT_SORTER_IR = 32;
static constexpr uint8_t TID_TREAT_THROWER_IR = 33;
static constexpr uint8_t TID_THERMAL_ARRAY = 34;
static constexpr uint8_t TID_NAV_BUTTON = 35;
static constexpr uint8_t TID_CMD_PUMP = 36;
static constexpr uint8_t TID_CMD_LID_1 = 37;
static constexpr uint8_t TID_CMD_LID_2 = 38;
static constexpr uint8_t TID_CMD_DISPLAY = 39;
static constexpr uint8_t TID_CMD_LED = 40;
static constexpr uint8_t TID_OVERBOUND = 41;

static constexpr uint8_t TOPIC_COUNT = 42;

// ── The Registry ────────────────────────────────────────────────────────────

// clang-format off
static constexpr std::array<TopicDescriptor, TOPIC_COUNT> TOPIC_REGISTRY = {{
    // ── Sensor Data (/sensors/...) ──────────────────────────────────────
    //  ID  Category               Policy                       Source               Topic                                      Thresh  Period    SID
    {  0,  TopicCategory::ANALOG,  PublishPolicy::ON_THRESHOLD, TopicSource::UART,   "/sensors/food_weight/bowl_1",              1.0f,   5000,   SID_LOAD_LEFT    },
    {  1,  TopicCategory::ANALOG,  PublishPolicy::ON_THRESHOLD, TopicSource::UART,   "/sensors/food_weight/bowl_2",              1.0f,   5000,   SID_LOAD_RIGHT   },
    {  2,  TopicCategory::ANALOG,  PublishPolicy::ON_THRESHOLD, TopicSource::UART,   "/sensors/water_level/tank",                0.5f,   5000,   SID_WATER_LEVEL  },
    {  3,  TopicCategory::ANALOG,  PublishPolicy::ON_THRESHOLD, TopicSource::UART,   "/sensors/water_level/bowl",                0.5f,   3000,   SID_WATER_BOWL   },
    {  4,  TopicCategory::ANALOG,  PublishPolicy::ON_THRESHOLD, TopicSource::UART,   "/sensors/environment/humidity",            0.5f,  10000,   SID_HUMIDITY     },
    {  5,  TopicCategory::ANALOG,  PublishPolicy::ON_THRESHOLD, TopicSource::UART,   "/sensors/environment/temperature",         0.1f,  10000,   SID_TEMPERATURE  },
    {  6,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::UART,   "/sensors/camera_rotation/limit_switch_1",  0.0f,  10000,   SID_LIMIT_SW1    },
    {  7,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::UART,   "/sensors/camera_rotation/limit_switch_2",  0.0f,  10000,   SID_LIMIT_SW2    },
    {  8,  TopicCategory::ENCODER, PublishPolicy::CONTINUOUS,   TopicSource::UART,   "/sensors/camera_rotation/optical_encoder", 0.0f,      0,   SID_ENCODER      },
    {  9,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::UART,   "/sensors/camera_rotation/home",            0.0f,      0,   SID_HOME_SENSOR  },
    // ── System (/system/...) ────────────────────────────────────────────
    { 10,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::UART,   "/system/power/switch",                     0.0f,      0,   SID_POWER_SW     },
    { 11,  TopicCategory::ANALOG,  PublishPolicy::ON_THRESHOLD, TopicSource::UART,   "/system/power/battery_level",              1.0f,  60000,   SID_BATTERY      },
    { 12,  TopicCategory::ANALOG,  PublishPolicy::PERIODIC,     TopicSource::SYSTEM, "/system/time/clock",                       0.0f,  1000,   -1               },
    { 13,  TopicCategory::HEARTBEAT, PublishPolicy::PERIODIC,     TopicSource::UART,   "/system/device/heartbeat",                 0.0f,  1000,   SID_HEARTBEAT    },
    { 14,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::SYSTEM, "/system/connectivity/state",               0.0f,  30000,   -1               },

    // ── Status (/status/...) ────────────────────────────────────────────
    { 15,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::UART,   "/status/lid/1",                            0.0f,      0,   PID_LID1_STEPPER },
    { 16,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::UART,   "/status/lid/2",                            0.0f,      0,   PID_LID2_STEPPER },
    { 17,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::UART,   "/status/water_pump",                       0.0f,      0,   PID_PUMP         },
    { 18,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::UART,   "/status/camera_rotation/stepper_motor",    0.0f,      0,   PID_CAMERA_STEPPER },
    { 19,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::UART,   "/status/display/seven_segment",            0.0f,      0,   PID_DISPLAY      },
    { 20,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::UART,   "/status/led_indicator",                    0.0f,      0,   PID_INDICATOR_LED},

    // ── Commands (/commands/...) ──────────────────────────────────────────
    { 21,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/camera_rotation",                0.0f,      0,   PID_CAMERA_STEPPER },
    { 22,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/feed",                           0.0f,      0,   -1                 },
    { 23,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/treat/dispense",                 0.0f,      0,   -1                 },
    { 24,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/photo_capture",                  0.0f,      0,   -1                 },
    { 25,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/live_session/start",             0.0f,      0,   -1                 },
    { 26,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/live_session/end",               0.0f,      0,   -1                 },
    { 27,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/camera/ir_control",              0.0f,      0,   -1                 },
    { 28,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/audio/speakers",                 0.0f,      0,   -1                 },
    { 29,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/settings/apply",                 0.0f,      0,   -1                 },
    { 30,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/firmware/update",                0.0f,      0,   -1                 },
    
    // ── Radxa Drivers Sensors (/sensors/...) ─────────────────────────────
    { 31,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::SYSTEM, "/sensors/treat/level_indicator_ir",        0.0f,   1000,   -1                 },
    { 32,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::SYSTEM, "/sensors/treat/sorter_ir",                 0.0f,   1000,   -1                 },
    { 33,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::SYSTEM, "/sensors/treat/thrower_ir",                0.0f,   1000,   -1                 },
    { 34,  TopicCategory::THERMAL, PublishPolicy::PERIODIC,     TopicSource::SYSTEM, "/sensors/thermal/ir_array",                0.0f,    100,   -1                 },
    { 35,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::UART,   "/sensors/nav_button",                      0.0f,      0,   SID_NAV_BUTTON    },
    // ── Actuator Commands (MCU Bound) ───────────────────────────────────
    { 36,  TopicCategory::DIGITAL, PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/pump",                           0.0f,      0,   PID_PUMP          },
    { 37,  TopicCategory::DIGITAL, PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/lid/1",                          0.0f,      0,   PID_LID1_STEPPER  },
    { 38,  TopicCategory::DIGITAL, PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/lid/2",                          0.0f,      0,   PID_LID2_STEPPER  },
    { 39,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/display",                        0.0f,      0,   PID_DISPLAY       },
    { 40,  TopicCategory::ANALOG,  PublishPolicy::ON_UPDATE,    TopicSource::SYSTEM, "/commands/led",                            0.0f,      0,   PID_INDICATOR_LED },
    { 41,  TopicCategory::DIGITAL, PublishPolicy::ON_CHANGE,    TopicSource::SYSTEM, "/system/reserved/overbound",               0.0f,      0,   -1                 },
}};
// clang-format on

// ── Lookup Functions ────────────────────────────────────────────────────────

// O(1) lookup by topic ID (direct array index)
inline const TopicDescriptor &lookup_by_topic_id(uint8_t tid) {
  // Bounds-safe: clamp to reserved slot if out of range
  if (tid >= TOPIC_COUNT) {
    return TOPIC_REGISTRY[TID_OVERBOUND];
  }
  return TOPIC_REGISTRY[tid];
}

// O(1) lookup by sensor ID — returns pointer to matching TopicDescriptor,
// or nullptr if no topic maps to this sensor ID.
// Uses a precomputed static LUT for zero-cost dispatch.
inline const TopicDescriptor *lookup_by_sensor_id(uint8_t sid) {
  // Static LUT: sensor_id (0–15) → topic_id index (or 0xFF if unmapped)
  static constexpr std::array<uint8_t, SID_COUNT> SID_TO_TID = {{
      TID_FOOD_WEIGHT_BOWL_1, // SID_LOAD_LEFT    → 0
      TID_FOOD_WEIGHT_BOWL_2, // SID_LOAD_RIGHT   → 1
      TID_WATER_LEVEL_TANK,   // SID_WATER_LEVEL  → 2
      TID_WATER_LEVEL_BOWL,   // SID_WATER_BOWL   → 3
      TID_HUMIDITY,           // SID_HUMIDITY     → 4
      TID_TEMPERATURE,        // SID_TEMPERATURE  → 5
      TID_LIMIT_SWITCH_1,     // SID_LIMIT_SW1    → 6
      TID_LIMIT_SWITCH_2,     // SID_LIMIT_SW2    → 7
      TID_OPTICAL_ENCODER,    // SID_ENCODER      → 8
      TID_HOME_SENSOR,        // SID_HOME_SENSOR  → 9
      TID_POWER_SWITCH,       // SID_POWER_SW     → 10
      TID_BATTERY_LEVEL,      // SID_BATTERY      → 11
      TID_HEARTBEAT,          // SID_HEARTBEAT    → 13
      0xFF,                   // 13 (Reserved)
      TID_NAV_BUTTON,         // SID_NAV_BUTTON   → 35 (0x0E)
      0xFF,                   // 15
  }};

  if (sid >= SID_COUNT) {
    return nullptr;
  }

  uint8_t tid = SID_TO_TID[sid];
  if (tid == 0xFF || tid >= TOPIC_COUNT) {
    return nullptr;
  }
  return &TOPIC_REGISTRY[tid];
}

// O(1) lookup by peripheral ID
inline const TopicDescriptor *lookup_by_peripheral_id(uint8_t pid) {
  // 4-bit field implies max 16 peripherals
  if (pid >= 16)
    return nullptr;

  static constexpr std::array<uint8_t, 16> PID_TO_TID = {
      {TID_WATER_PUMP,    // PID_PUMP           → 17
       TID_LID_1,         // PID_LID1_STEPPER   → 15
       TID_LID_2,         // PID_LID2_STEPPER   → 16
       TID_STEPPER_MOTOR, // PID_CAMERA_STEPPER → 18
       TID_SEVEN_SEGMENT, // PID_DISPLAY        → 19
       TID_LED_INDICATOR, // PID_INDICATOR_LED  → 20
       0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}};

  uint8_t tid = PID_TO_TID[pid];
  if (tid == 0xFF || tid >= TOPIC_COUNT)
    return nullptr;
  return &TOPIC_REGISTRY[tid];
}

} // namespace oro
#endif // DATA_TOPIC_REGISTRY_HPP
